import axios from 'axios';
import { promises as fs } from 'fs';
import path from 'path';
import { logger } from '../utils/logger.js';

/**
 * Base image class returned from Gemini
 */
export class Image {
  url: string;
  title: string;
  alt: string;
  proxy?: string;

  constructor(data: { url: string; title?: string; alt?: string; proxy?: string }) {
    this.url = data.url;
    this.title = data.title ?? '[Image]';
    this.alt = data.alt ?? '';
    this.proxy = data.proxy;
  }

  toString(): string {
    const truncatedUrl =
      this.url.length <= 20
        ? this.url
        : `${this.url.substring(0, 8)}...${this.url.substring(this.url.length - 12)}`;
    return `Image(title='${this.title}', alt='${this.alt}', url='${truncatedUrl}')`;
  }

  /**
   * Save the image to disk
   */
  async save(options?: {
    path?: string;
    filename?: string;
    cookies?: Record<string, string>;
    verbose?: boolean;
    skipInvalidFilename?: boolean;
  }): Promise<string | null> {
    const {
      path: savePath = 'temp',
      filename: providedFilename,
      cookies,
      verbose = false,
      skipInvalidFilename = false,
    } = options ?? {};

    let filename = providedFilename || this.url.split('/').pop()?.split('?')[0] || 'image';

    // Validate filename
    const filenameMatch = filename.match(/^(.*\.\w+)/);
    if (!filenameMatch) {
      if (verbose) {
        logger.warn(`Invalid filename: ${filename}`);
      }
      if (skipInvalidFilename) {
        return null;
      }
    } else {
      filename = filenameMatch[1];
    }

    try {
      const headers: Record<string, string> = {};
      if (cookies) {
        headers['Cookie'] = Object.entries(cookies)
          .map(([key, value]) => `${key}=${value}`)
          .join('; ');
      }

      const response = await axios.get(this.url, {
        responseType: 'arraybuffer',
        headers,
        proxy: this.proxy
          ? {
              protocol: new URL(this.proxy).protocol.replace(':', ''),
              host: new URL(this.proxy).hostname,
              port: parseInt(new URL(this.proxy).port),
            }
          : undefined,
      });

      const contentType = response.headers['content-type'];
      if (contentType && !contentType.includes('image')) {
        logger.warn(`Content type of ${filename} is not image, but ${contentType}.`);
      }

      await fs.mkdir(savePath, { recursive: true });

      const destPath = path.join(savePath, filename);
      await fs.writeFile(destPath, response.data);

      const absolutePath = path.resolve(destPath);
      if (verbose) {
        logger.info(`Image saved as ${absolutePath}`);
      }

      return absolutePath;
    } catch (error) {
      if (axios.isAxiosError(error)) {
        throw new Error(
          `Error downloading image: ${error.response?.status} ${error.response?.statusText}`
        );
      }
      throw error;
    }
  }
}

/**
 * Image retrieved from web
 * Returned when asking Gemini to "SEND an image of [something]"
 */
export class WebImage extends Image {
  constructor(data: { url: string; title?: string; alt?: string; proxy?: string }) {
    super(data);
  }
}

/**
 * Image generated by ImageFX, Google's AI image generator
 * Returned when asking Gemini to "GENERATE an image of [something]"
 */
export class GeneratedImage extends Image {
  cookies: Record<string, string>;

  constructor(data: {
    url: string;
    title?: string;
    alt?: string;
    proxy?: string;
    cookies: Record<string, string>;
  }) {
    super(data);

    if (!data.cookies || Object.keys(data.cookies).length === 0) {
      throw new Error(
        'GeneratedImage is designed to be initialized with same cookies as GeminiClient.'
      );
    }
    this.cookies = data.cookies;
  }

  /**
   * Save the generated image to disk
   */
  async save(options?: {
    path?: string;
    filename?: string;
    verbose?: boolean;
    skipInvalidFilename?: boolean;
    fullSize?: boolean;
  }): Promise<string | null> {
    const { fullSize = true, ...restOptions } = options ?? {};

    let url = this.url;
    if (fullSize) {
      url += '=s2048';
    }

    const filename =
      restOptions.filename ||
      `${new Date().toISOString().replace(/[-:]/g, '').split('.')[0]}_${url.slice(-10)}.png`;

    const originalUrl = this.url;
    this.url = url;

    try {
      return await super.save({
        ...restOptions,
        filename,
        cookies: this.cookies,
      });
    } finally {
      this.url = originalUrl;
    }
  }
}
